### ISSUE TITLE
If an image is created that is too large, Ray doesn't complain.

### ISSUE THREAD

**Issue by bil-bas** [Mon-Ouie/ray#16]
Image.new([10000, 10000]) is accepted, but the size of the image is given as (0, 0) (so I assume it doesn't create a working image). Perhaps it should raise an exception if the image requested is too large to handle? Also might be nice to have a constant on Image that tells us the max size that we can ask for so we don't have to guess :)

**Comment by bil-bas** [comment]
Seems to be maxed out at 8192x8192 on my machine, but _probably_ should be a constant value on all machines and platforms in Ray to make developing simpler (I think it is 1022x1022 on Gosu).

**Comment by bil-bas** [comment]
Also doesn't complain if you create an image that is 0x0 (which I know when I tried it in Gosu/Linux, segfaulted, but was OK on windows. Another exception there, I think).

**Comment by Mon-Ouie** [comment]
I don't think there should be an arbitrary limit to the size of an image. I set the maximal size to whatever is the maximum size for OpenGL. Actually, Say sets an error when you create a bigger image, I just forgot to check the error in Ray. :)
