### ISSUE TITLE
A Scene class doesn't seem to have 'always' available

### ISSUE THREAD

**Issue by bil-bas** [Mon-Ouie/ray#18]
In the DSL, you can hook into the "update" using "always do ...end". If using a class inheriting Scene, I can't see a way to hook into that per-frame update (I can override #setup and #render to hook into those effects, but there isn't a #always to override)

**Comment by Mon-Ouie** [comment]
You can call always:

``` ruby
def register
  always do
    # stuff
  end
end
```
