### ISSUE TITLE
Can't set long arrays or arrays of arrays in Shaders

### ISSUE THREAD

**Issue by bil-bas** [Mon-Ouie/ray#19]
Although you can pass vec2/3/4 (or integer or boolean arrays up to size 4) you can't pass longer arrays in.
Can't pass arrays of arrays in (such as an array of vec2/3/4).

**Comment by Mon-Ouie** [comment]
Actually, it is possible to set those; and making Ray able to set them from an array would make parsing of arguments much more complicated. We can simply do this instead:

``` ruby
shader["foo[0]"] = 3

0.upto(10) do |i|
  shader["attribute[#{i}]"] = [0, 1, 2]
end
```
