### ISSUE TITLE
Set a default font

### ISSUE THREAD

**Issue by bil-bas** [Mon-Ouie/ray#24]
Usually an application will use a single font throughout (or SHOULD do). Having to always use the option `font: "path/to/font.ttf"` in every Text created is a bit cumbersome if the value is always the same. Text.default_font_name= could be used to set the default font globally.

This could also apply to default font size, but that is a lot less important since it is usual to have multiple sizes of font in a GUI/overlay.

**Comment by Mon-Ouie** [comment]
Not really fond of that idea. As a sidenote, It's valid to have different fonts for titles and texts, IMO.
