### ISSUE TITLE
A duplicated Text ignores #color=

### ISSUE THREAD

**Issue by bil-bas** [Mon-Ouie/ray#25]
I duplicated a Text object, then attempted to change its colour, but it stayed the same colour as the original. #color works normally for non-duped Text objects, though.

**Comment by Mon-Ouie** [comment]
I can't reproduce this. It works in tests. I also looked at the code, the color is simply copied, nothing else happens:

``` ruby
pry(main)> text = Ray::Text.new "test"
=> text("test")
pry(main)> text.color = Ray::Color.green
=> RGBA(0, 255, 0, 255)
pry(main)> duplicate = text.dup
=> text("test")
pry(main)> duplicate.color
=> RGBA(0, 255, 0, 255)
pry(main)> duplicate.color = Ray::Color.blue
=> RGBA(0, 0, 255, 255)
pry(main)> duplicate.color
=> RGBA(0, 0, 255, 255)
```

**Comment by bil-bas** [comment]
I can definitely replicate the Text#color= thing in my game. The #color is changed, as you've proven, but it still _displays_ in the old color.
