### ISSUE TITLE
Optimise Vectors

### ISSUE THREAD

**Issue by bil-bas** [Mon-Ouie/ray#28]
Using Ruby's Profile gem on my game, I found that a significant number of the high-cost methods were on Vector2 and Vector3 (here showing those operations that used 0.99-9.02% of overall run-time; Vector operations, although relatively fast, appear here because they are called a huge number of times). By implementing more of the VectorN methods in C, such as like #-, #length, #dist, a significant amount of time could be saved (compared to optimising the already super-fast drawing). As can be seen, the operations already implemented in C were very much faster than the ones that are still in Ruby.

<pre>
  %   cumulative   self              self     total
 time   seconds   seconds    calls  ms/call  ms/call  name

  9.02     3.84      3.84     3282     1.17    16.71  Range#each
  8.15     7.30      3.46    28854     0.12     0.32  SkewedMap#tile_at_grid
  6.89    10.23      2.93    95508     0.03     0.04  Comparable.between?
  5.81    12.70      2.47   102033     0.02     0.03  Ray::Vector2#[]
  5.21    14.91      2.21    18900     0.12     0.31  Map#tile_at_grid
  4.57    16.86      1.95    16384     0.12     0.18  Ray::Vector2#length
  3.66    18.42      1.56      299     5.21    30.75  Kernel.gem_original_require
  3.46    19.89      1.47   152390     0.01     0.01  Ray::Vector2#x
  3.24    21.27      1.38   154379     0.01     0.01  Ray::Vector2#y
  3.23    22.64      1.37    16783     0.08     0.17  Ray::Vector2#-
  3.00    23.92      1.28   190491     0.01     0.01  Float#<=>
  2.39    24.93      1.02    55850     0.02     0.05  Array#to_vector2
  2.10    25.82      0.89    58870     0.02     0.02  Array#[]
  1.97    26.66      0.84     7764     0.11     2.99  Array#each
  1.80    27.43      0.77   112531     0.01     0.01  Fixnum#-
  1.72    28.16      0.73   102033     0.01     0.01  Ray::Vector2#initialize
  1.40    28.75      0.59    25264     0.02     2.77  Class#new
  1.25    29.29      0.53    56178     0.01     0.01  Float#*
  1.10    29.76      0.47    16384     0.03     0.37  Ray::Vector2#dist
  0.99    30.18      0.42    32049     0.01     0.01  Ray::Vector2#to_vector2
</pre>

**Comment by Mon-Ouie** [comment]
Doing math in C just for speed seems silly to me. Method calls always have overhead in Ruby, I could just as well rewrite _everything_ in C then.

Optimizations to the graphics aren't related to the use of C. It's optimized by using other methods for drawing. Changing the algorithm is a better way than just rewriting everything in a faster language.

**Comment by bil-bas** [comment]
Making each of those Vector methods as little as 2x faster would give an extra few FPS in this example (a similar improvement to all rendering operations). My intention was to show the actual bottlenecks in a "real" game and thus where optimisation would make a real difference. These methods can't be optimised algorithmically in Ruby since they are relatively simple, so the only option, in order to improve performance, is to rewrite in C.

In my previous suggestion, `Ray::Rect#collide?` could be significantly speeded up just algorithmically, which was great. It would be called a lot in games with a lot of collision checking and showed up as a bottleneck in a different test-game that did a lot more collision checking.

One could argue, however, that in my highly pixelated games (Wrath is zoomed by 4; Hoops and Zed & Ginger by 8), the significance of drawing vs. computation is heavily skewed, since the number of pixels being rendered is massively lower than in a non-zoomed game. Thus, when I look at Gosu/Ray it seems that rendering is trivial compared to computation.

**Comment by Mon-Ouie** [comment]
Yes, they can be optimized algorithmically. The algorithm that calls them can perhaps be optimized. Also, you can sometimes use the square of the length instead of the length itself, which avoids having to compute a square root.

So, I definitely won't rewrite more than needed in C.
