### ISSUE TITLE
The more Polygons created, the slower creation is

### ISSUE THREAD

**Issue by bil-bas** [Mon-Ouie/ray#35]
Although this is an extreme example, any large scale game, that creates a large number of objects over a significant amount of time will probably feel the effect of whatever is causing this slowdown. Not tested with other drawables. Perhaps they are broken too?

I felt the effect of this on frame-rate, just creating 10 objects a frame after a few minutes. Not unreasonable if you are creating particles, for example (though you could go to the effort of caching them...but still).

Not a high priority, but could be a simple fix :)

``` Ruby
require 'ray'

# The more objects you create, the more time each creation takes.
# For me, this will slowly go down from 45fps to 5fps (and ~80k objects created).
# Pressing space lets the FPS just shoot immediately back up to 45.
#

Ray.game "Invisible text" do
  register { add_hook :quit, method(:exit!) }

  scene :scene do  
    @grind = true
    @text = text "0", at: [100, 100], size: 30
    @num_objects = 0

    on :key_press, key(:space) do
      @grind = false
    end

    always do
      @rects = []

      if @grind
        100.times do    
          @rects << Ray::Polygon.rectangle([0, 0, 100, 100])
        end
        @num_objects += 100
        @text.string = @num_objects.to_s
      end

      sleep 0.02
    end  

    render do |win|
      if @grind
        @rects.each {|rect| win.draw rect }
      end
      win.draw @text
    end
  end

  scenes << :scene
end
```

**Comment by Mon-Ouie** [comment]
> > though you could go to the effort of caching them...but still
> > You should, as drawing a drawable for the first time is slow.

So as discussed on IRC, it's not a bug that performance decrease progressively, and not due to Ray directly.
