### ISSUE TITLE
Different line behaviour with add_point between filled and unfilled

### ISSUE THREAD

**Issue by Bediko** [Mon-Ouie/ray#38]
Hello.
I made this Tetris-Block: https://gist.github.com/1105083
When it is just outlined, it looks perfect but wenn I let it fill, one line is not perfect anymore. 

I hope its a bug and not that I am just too stupid.

**Comment by Mon-Ouie** [comment]
Hey,

This is not a bug. The Polygon class is only guaranteed to work with convex polygons — and yours is concave. Lining up the point still works, but filling the content is trickier (and, thus, may work sometimes, but not for any set of point).

Anyway, it is quite easy to create your L-block with two rectangles. ;)
