### ISSUE TITLE
sprite_animation doesn't spend time on the last frame.

### ISSUE THREAD

**Issue by bil-bas** [Mon-Ouie/ray#4]
A sprite_animation should stay on the last frame for the same amount of time as the other frames. At the moment, if a 3-frame animation has a duration of 12s, it will animate at 6, 12, then finish just as the final frame is shown. What I expect is 4, 4, 4s for each frame. This doesn't generally matter, but it does matter if you are looping the animation or moving on to another animation after the animation is finished.

**Comment by Mon-Ouie** [comment]
Fixed ;)
