### ISSUE TITLE
Text "pinkified" when saved

### ISSUE THREAD

**Issue by bil-bas** [Mon-Ouie/ray#40]
Text rendered to an image or created with Window#to_image has text incorrectly coloured.

Screenshot: http://cl.ly/1N0V2O2n3V1N1k39172n
Saved image: http://cl.ly/3X1n0S2n033E1U1p2s3p

**Comment by Mon-Ouie** [comment]
Seems to be related to the use of the alpha channel, but it only happens when saving as a BMP here.
Indeed, I now checked the documentation. BMP files are outpt without an alpha channel.
