### ISSUE TITLE
Leaving a Game doesn't close its Window

### ISSUE THREAD

**Issue by bil-bas** [Mon-Ouie/ray#45]
When I closed a Game (with `pop_scene` in the root scene) and opened another window, it showed a zombie window until the program exited.

Manually closing the window after I popped meant the existing window was closed properly and the new one worked fine.

``` Ruby
pop_scene
window.close
```

**Comment by Mon-Ouie** [comment]
That's not a bug, the window should get closed when it is garbage collected. It also wouldn't be appropriate to auotomatically close windows that the game did not open.

**Comment by bil-bas** [comment]
But surely the game did open the window, so I'd expect it to close it again. As it is, it will be auto-closed when Ruby closes, but doesn't seem to before that. I just have an expectation that if something creates something transparently that it also destroys it transparently.

**Comment by Mon-Ouie** [comment]
GC will happen transparently at some point — provided no references to the window are kept.
