### ISSUE TITLE
Assign rect position's components value

### ISSUE THREAD

**Issue by Nerian** [Mon-Ouie/ray#49]
Hello,

Take a look a this:

``` ruby
ruby-1.9.2-p290 :018 > a = Ray::Polygon.circle([200, 200], 10, Ray::Color.blue)
 => #<Ray::Polygon:0x007f8b88b30400> 
ruby-1.9.2-p290 :019 > a.pos
 => (0, 0) 
ruby-1.9.2-p290 :020 > a.pos.x = 8
 => 8 
ruby-1.9.2-p290 :021 > a.pos
 => (0, 0) 
```

`a.pos` should be 8, right?

I am using Ray to make a Liquid Wars clone  https://github.com/Nerian/Pugnacious-Juices   You are creating an awesome library!

**Comment by Mon-Ouie** [comment]
No, a.pos (and other things that return vectors) return a copy of the vector used internally (it would be really hard to ensure the vector won't be freed if it was the actual vector). You can simply use `Drawable#x=` :

``` ruby
a.x = 8
a.pos #=> (8, 0)
```

Thanks for the comment ;)
