### ISSUE TITLE
Trouble installing native extensions on Linux 64 bit

### ISSUE THREAD

**Issue by PragTob** [Mon-Ouie/ray#50]
Hey there,

I am using Linux Mint 11 64 bit (which is based upon Ubuntu 11.04) and the installation of Ray always aborts. I got all dependencies (I think) installed but now make finishes with an error.

```
say_context.c: In function ‘say_context_glew_init’:
say_context.c:231:3: error: ‘glVertexAttribDivisor’ undeclared (first use in this function)
say_context.c:231:3: note: each undeclared identifier is reported only once for each function it appears in
make: *** [say_context.o] Error 1
```

However see this gist for the whole console output:  https://gist.github.com/1216617

I hope I didn't simply miss a dependency.

**Comment by Mon-Ouie** [comment]
Basically, you did. .p

You have the right dependency, but not the right version. You need GLEW 1.6 at least to be able to compile Ray.

**Comment by PragTob** [comment]
well thanks for the quick feedback. Unfortunately glew 1.6 isn't in my repos.. I'll see if I can get it from somewhere else.

I'll leave this open and close it when it runs with 1.6 or I don't find an easy way to get glew 1.6 without messing with my packages.

Thanks!

**Comment by davesmylie** [comment]
PragTob - if you're running on debian/ubuntu, I think you'll just need to install manually from: 

http://sourceforge.net/projects/glew/files/glew/1.7.0/glew-1.7.0.tgz/download

It's a pretty painless install. If you're gonna wait for it to be added, it may be some time....

**Comment by PragTob** [comment]
Hey guys, 

thanks for the support. I was rather busy (hard ruby course) at the time so sorry for the very late answer. With some workarounds I managed to get ray working, thank you very much! Now that I have the time I might get around to play a bit with ray!

cheerio!
