### ISSUE TITLE
Rectangle size

### ISSUE THREAD

**Issue by Nerian** [Mon-Ouie/ray#51]
Hello,

``` ruby
@point = Ray::Polygon.rectangle([10,10,11,11])
```

This creates a rectangle. The problem is that it is too big. How could I make it smaller? 

I would like it to be around 4 pixels.

Thanks!

**Comment by Mon-Ouie** [comment]
You could set scale to less than one :

``` ruby
@point.scale = [0.5, 0.5] # half the size
```

Or you could set the size to 2 or 4 when you create it :

``` ruby
@point = Ray::Polygon.rectangle [10, 10, 1, 1]
```

The two last numbers are respectively the width and the height of the rect.

**Comment by Nerian** [comment]
Perfect!

Thanks!
