### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by practicingruby** [Mon-Ouie/ray#53]
It's unclear what license Ray is under. Can you add a LICENSE file or something to the README?

**Comment by Mon-Ouie** [comment]
I added the zlib license — which looks permissive enough. The lack of license was kind of related to me thinking anyone should be allowed to do whatever they want. ;)

**Comment by practicingruby** [comment]
Great, thanks! FWIW at least in the US a lack of a license means "All rights reserved", not "Do what you want".
