### ISSUE TITLE
Ray doesn't work with JRuby on Windows

### ISSUE THREAD

**Issue by thisredone** [Mon-Ouie/ray#57]
Maybe I'm missing something but I can't get it to work.
I have also written on stackoverflow:
 http://stackoverflow.com/questions/9894475/ray-on-jruby-opengl

Are there any steps needed in order for it to work with JRuby? On HN you said you've tested ray with it so I'm really curious.

**Comment by Mon-Ouie** [comment]
Well, I did test Ray with JRuby — but that was with Linux :p I didn't assume `RUBY_PLATFORM` be changed by JRuby.

**Comment by thisredone** [comment]
Do you have an idea how to make it work on Windows?

**Comment by Mon-Ouie** [comment]
Now that JRuby doesn't support C extensions anymore, this has become irrelevant.
