### ISSUE TITLE
Errors with Ray and Ruby 2.0 because of Iconv (deprecated in Ruby 1.9.3)

### ISSUE THREAD

**Issue by illtellyoulater** [Mon-Ouie/ray#60]
C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- iconv
(LoadError)
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/ray-0.2.0/lib/ray/ray.rb:2:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/ray-0.2.0/lib/ray.rb:1:in`<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in`rescue in require'
        from C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from drawing_with_ray.rb:25:in`<main>'
- Windows 7
- Ruby 2.0.0p353
- ray-0.2.0

**Comment by illtellyoulater** [comment]
It seems that removing require 'iconv' in ray/ray.rb will work just good?

**Comment by Mon-Ouie** [comment]
This has been done a while ago (it only requires iconv for RUBY_VERSION < "1.9", but the gem hadn't been updated. I just pushed a new release that should fix it.
